# Generated by Django 2.0.8 on 2018-11-21 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NGSapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='Pool_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NGSapp.Pool'),
        ),
    ]
