# Generated by Django 2.0.8 on 2018-11-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGSapp', '0002_auto_20181121_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='runDate',
            new_name='RunDate',
        ),
    ]
